# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9a169477e8834d9d762e52a32cabb0f5e3123793097e8c556b9ff94b0267a834e153c124b24ca558e5d1c68bcc9af0c54293dbffd3ea259213f156d09511046

test:
  secret_key_base: 87074fbc69ebc5d58dc40ba726c0efb08bd09a651d6f16abacdfc5f81565b758f91719842823e494b8362d8cf5d590f0f25a04b233ef997433f2b5d1c10285ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
